[project]
name = "expense-log-mcp"
version = "0.1.0"
description = "A MCP server that provides tools for logging expenses."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.12.4",
    "prisma>=0.15.0",
    "python-dotenv>=1.1.1",
]
